=== cyberrangecz/backend-training/kypo2-service-training/src/main/resources/questions-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
        "required": [ "question_type", "text", "points", "penalty", "order", "answer_required"],
        "properties": {
          "question_type": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "points": {
            "type": "integer"
          },
          "penalty": {
            "type": "integer"
          },
          "order": {
            "type": "integer"
          },
          "answer_required": {
            "type": "boolean"
          },
          "correct_choices": {
            "type": "array",
            "items": [
              {
                "type": "string"
              }
            ]
          },
          "choices": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["order", "text"],
              "properties": {
                "order": {
                  "type": "integer"
                },
                "text": {
                  "type": "string"
                },
                "is_correct": {
                  "type": "boolean"
                },
                "pair": {
                  "type": "integer"
                }
              },
              "oneOf": [
                {"required": [ "pair" ]},
                {"required": [ "is_correct" ]}],
              "additionalProperties": false
            }
          }
        },
      "additionalProperties": false,
        "oneOf": [
          {"required": [ "choices" ]},
          {"required": [ "correct_choices" ]}
        ]
  }
}

=== cyberrangecz/backend-training/kypo2-service-training/src/test/resources/questions.json
[
  {
    "question_type":             "FFQ",
    "text":             "Write name of one malicious software?",
    "points":           6,
    "penalty":          3,
    "order":            0,
    "answer_required":         true,
    "correct_choices":  [
                        "viruses",
                        "trojans",
                        "worms",
                        "bots"
                      ]
  },
  {
    "question_type":             "MCQ",
    "text":             "Among the following choices, select all the possible methods of prevention against an unwanted file upload.",
    "points":           4,
    "penalty":          2,
    "order":            1,
    "answer_required":         true,
    "choices":          [
                          {
                            "order":        0,
                            "text":         "whitelisting file extensions",
                            "is_correct":    true
                          },
                          {
                            "order":         1,
                            "text":         "limiting maximum file size",
                            "is_correct":    true
                          },
                          {
                            "order":        2,
                            "text":        "using database triggers",
                            "is_correct":   false
                          },
                          {
                            "order":        3,
                            "text":         "saving data to an NTFS volume",
                            "is_correct":    false
                          }
                        ]
  },
  {
    "question_type":             "EMI",
    "text":             "Connect the following exemplary situations with the corresponding type of password attack.",
    "points":           3,
    "penalty":          1,
    "order":            2,
    "answer_required":         true,
    "choices":          [
                          {
                            "order":        0,
                            "text":         "trying all possible alphanumeric combinations of 8 characters",
                            "pair":         6
                          },
                          {
                            "order":        1,
                            "text":         "trying common words of English language",
                            "pair":         4
                          },
                          {
                            "order":        2,
                            "text":         "looking up the value of a hashed password",
                            "pair":         7
                          },
                          {
                            "order":        3,
                            "text":         "tricking a user into giving away his password by posing as a service administrator",
                            "pair":         5
                          },
                          {
                            "order":        4,
                            "text":         "dictionary attack",
                            "pair":         1
                          },
                          {
                            "order":        5,
                            "text":         "social engineering",
                            "pair":         3
                          },
                          {
                            "order":        6,
                            "text":         "brute force attack",
                            "pair":         0
                          },
                          {
                            "order":        7,
                            "text":         "rainbow table attack",
                            "pair":         2
                          }
                        ]
  }
]
